export const PATH_NAMES = {
  HOME: '/',
 LOGIN: '/login',
 SIGNUP: '/signup',
  MARKETPLACE: '/marketplace',
  PRODUCT_DETAIL: '/product',
  ABOUT: '/about',
 ADMIN: '/admin',
 PROFILE: '/profile',
  CART: '/cart',
  FARMLIST: '/farmlist',
  MAP_AREA: '/map-area',
  STAFF: '/staff',
  CREATE_FARM: '/create-farm',
  UPDATE_FARM: '/update-farm',
  FARM_DETAIL: '/farm-detail',
  // Vendor routes
  VENDOR_DASHBOARD: '/vendor/dashboard',
  VENDOR_PRODUCTS: '/vendor/products',
  VENDOR_REGISTRATIONS: '/vendor/registrations',
  VENDOR_WALLET: '/vendor/wallet',
  VENDOR_INFO: '/vendor/info',
};
